---

extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  colons:
    max-spaces-after: 1
    level: error
  commas:
    level: error
  comments:
    level: error
  comments-indentation:
    level: warning
  document-start: disable
  empty-lines:
    max: 2
    max-end: 2
    level: error
  hyphens:
    level: error
  line-length:
    max: 140
    level: error
    allow-non-breakable-inline-mappings: true
  truthy: disable

  indentation:
    level: warning
  new-line-at-end-of-file:
    level: warning
  trailing-spaces:
    level: warning
