---
title: "C4 Desktop"
cluster: "c4"
submit: "submit/c4_submit.yml.erb"
attributes:
  desktop: "mate"
  bc_vnc_idle: 0
  bc_queue:
    label: "Partition"
  bc_vnc_resolution:
    required: true
  node_type: null
  slurm_mem:
    widget: "number_field"
    max: 256
    min: 1
    step: 1
    value: 1
    label: "Memory (GiB)"
    help: "Enter a value in GiB between 1 and 256"
  slurm_cores:
    widget: "number_field"
    max: 64
    min: 1
    step: 1
    value: 1
    label: "Number of cores"
    help: "Enter a value between 1 and 64"
  slurm_scratch:
    widget: "number_field"
    max: 256
    min: 1
    step: 1
    value: 1
    label: "Scratch space (GiB)"
    help: "Enter a value between 1 and 2550 (1 GiB - 2.5 TiB)"          
form:
  - bc_vnc_idle
  - desktop
  - bc_num_hours
  - bc_queue
  - bc_vnc_resolution
  - slurm_mem
  - slurm_cores
  - slurm_scratch 
  