on: [push, pull_request]

name: yamllint

jobs:
  check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    name: yamllint

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install yamllint
          yamllint --version
          
      - name: yamllint
        run: |
          yamllint --version
          make yamllint
